### ISSUE TITLE
Error Counsul agent container.

### ISSUE THREAD

**Issue by admSpiker** [hakwerk/labca#104]
Good day. I really liked your project but Consul Agent container restarts with an error
`==> Starting Consul agent...
              Version: '1.15.4'
           Build Date: '2023-06-23 23:14:17 +0000 UTC'
              Node ID: '3060a990-1e3f-6a32-2af7-97cca607e1b1'
            Node name: 'c66cc4bb2eec'
           Datacenter: 'dc1' (Segment: '<all>')
               Server: true (Bootstrap: false)
          Client Addr: [0.0.0.0] (HTTP: 8500, HTTPS: -1, gRPC: 8502, gRPC-TLS: 8503, DNS: 53)
         Cluster Addr: 10.55.55.10 (LAN: 8301, WAN: 8302)
    Gossip Encryption: false
     Auto-Encrypt-TLS: false
     Reporting Enabled: false
            HTTPS TLS: Verify Incoming: false, Verify Outgoing: false, Min Version: TLSv1_2
             gRPC TLS: Verify Incoming: false, Min Version: TLSv1_2
     Internal RPC TLS: Verify Incoming: false, Verify Outgoing: false (Verify Hostname: false), Min Version: TLSv1_2

==> Log data will now stream in as it occurs:

2023-11-21T18:03:59.907Z [ERROR] agent: Error starting agent:
  error=
  | 2 errors occurred:
  | \t* listen udp 0.0.0.0:53: bind: permission denied
  | \t* listen tcp 0.0.0.0:53: bind: permission denied
`
Docker version 24.0.6, build ed223bc
Docker Compose version v2.21.0
os "CentOS Linux 7 (Core)"

**Comment by hakwerk** [comment]
It's just the vanilla consul container from Hashicorp. Maybe this https://github.com/hashicorp/docker-consul/issues/15 contains something useful?

**Comment by tjmullicani** [comment]
@admSpiker Try adding this to the docker-compose.yml file:
```yaml
services:
  bconsul:
    environment:
      - CONSUL_ALLOW_PRIVILEGED_PORTS=
```

![image](https://github.com/hakwerk/labca/assets/18095326/53e92b79-fbf5-4ac3-8ec5-61bdc0ba0ad6)

References:
https://github.com/docker/compose/issues/3877
https://github.com/docker-library/docs/pull/691/files
