### ISSUE TITLE
DNS Domain , CAA Record - Guidance

### ISSUE THREAD

**Issue by bugsbunny88** [hakwerk/labca#110]
In the docker-compose file , 
does one change the consul dns address to point to my firewall/ip at 192.168.1.1 ? 
and a host override back to the server running labca ?

I'm a bit stuck with the instructions and getting CAA record issues. Trying to setup labca on my home lan .

**Comment by hakwerk** [comment]
Normally you don't need to change the consul dns address.

Say that you installed LabCA on a server with IP address 192.168.1.20 and your internal DNS server is at 192.168.1.10. In that DNS server you have to create an A records for myca.mydomain.local pointing to 192.168.1.20.
After installing the LabCA software, in your browser you go to myca.mydomain.local (as your local machine should also know to lookup in the internal DNS server). After creating a user account, in the next screen of the LabCA setup you have to provide the IP address of the DNS server (192.168.1.10). Once the LabCA setup has been completed this is also available via the Manage menu item, on the Config tab.

I haven't had to setup any CAA records myself, but that may have to do with also setting up the appropriate records for the top-level domain (.local in this example).

Let me know if this helps or if you need more info.

**Comment by hakwerk** [comment]
I've never had a need for a wildcard certificate so I never really tried it. You may need to have to change the value of FAKE_DNS in the docker-compose.yml file for that. The comment there mentions it is needed for HTTP-01 challenge but I think they mean for DNS-01 challenge.
Your DNS server needs to have an API so the client (Caddy) can create the TXT record in DNS automatically.

When looking at the Caddy documentation it should be possible to configure the acme part once and then have as many hosts in your Caddyfile as you like and Caddy will request individual certificates for each of them automatically.

New certificates are requested over HTTPS and therefore Caddy needs to have your Root CA certificate so it can validate the LabCA server certificate.
