### ISSUE TITLE
Error in install last step  when Signing certificate...

### ISSUE THREAD

**Issue by tromanshow** [hakwerk/labca#116]
Hello when i try to install i got this error in /home/labca/nginx_data/ssl/acme_tiny.log : 

Wed Feb 28 12:43:42 UTC 2024
Parsing account key...
Parsing CSR...
Found domains: labca.home.arpa
Getting directory...
Directory found!
Registering account...
Already registered! Account ID: http://boulder:4001/acme/acct/1
Updated contact details:
mailto:<mymail@gmail.com>
Creating new order...
Order created!
Already verified: labca.home.arpa, skipping...
Signing certificate...
Traceback (most recent call last):
  File "/opt/labca/acme_tiny.py", line 199, in <module>
    main(sys.argv[1:])
  File "/opt/labca/acme_tiny.py", line 195, in main
    signed_crt = get_crt(args.account_key, args.csr, args.acme_dir, log=LOGGER, CA=args.ca, disable_check=args.disable_check, directory_url=args.directory_url, contact=args.contact, check_port=args.check_port)
  File "/opt/labca/acme_tiny.py", line 160, in get_crt
    _send_signed_request(order['finalize'], {"csr": _b64(csr_der)}, "Error finalizing order")
  File "/opt/labca/acme_tiny.py", line 60, in _send_signed_request
    return _do_request(url, data=data.encode('utf8'), err_msg=err_msg, depth=depth)
  File "/opt/labca/acme_tiny.py", line 46, in _do_request
    raise ValueError("{0}:\nUrl: {1}\nData: {2}\nResponse Code: {3}\nResponse: {4}".format(err_msg, url, data, code, resp_data))
ValueError: Error finalizing order:
Url: http://boulder:4001/acme/finalize/1/5
Data: b'{"protected": "eyJ1cmwiOiAiaHR0cDovL2JvdWxkZXI6NDAwMS9hY21lL2ZpbmFsaXplLzEvNSIsICJhbGciOiAiUlMyNTYiLCAibm9uY2UiOiAiX2p1M2tGRHN4WW1FX2NWQUZQUUxnS2tIVG85bV9QVWU3Z0tuTkNmXzRvckZuX2JhR0VrIiwgImtpZCI6ICJodHRwOi8vYm91bGRlcjo0MDAxL2FjbWUvYWNjdC8xIn0", "payload": "eyJjc3IiOiAiTUlJQ2NqQ0NBVm9DQVFBd0FEQ0NBU0l3RFFZSktvWklodmNOQVFFQkJRQURnZ0VQQURDQ0FRb0NnZ0VCQUtXS0RmeEhUVHVwOEg4YkdGU2JhZ1QtWDY1MnQyRFNCNDM3RkRVNzJjVmIzTmR0a01HbmxLcklqUk9ZSzA4eXdmUDRHRnhJY0dxb0FtemQ4YTlncElwU19hb1Ixa0JHNWRJWVBVSFhZMnVDRkZjMFFTUzVmRk1GQjlNakdzY3NnMVVOM0pQMlpqOGlGMUhoU3dVa2ZRVzRvSGN4akt0eFZkSDR2SG1RVEk4YUNjX2dlbWxKZ2o3WDVnLVpBSlNjUnE0MVhtcGMxOFRRemxNWDJkN2YtVEZHZDdZMDdFUF8xd09QbnYwUUJxdmNVZHdWZHZ6aXJQcjRJNDRUdmxIU3Y1QkVBdm50NDJJODktNTdxNElTbDZCNi1xTGNtXzB1bDJtQVNLaVdqR21GLVB0QjZhWTNPeTJ3X0thSU0yN2ZYQnpXQUVtdWlNNlcxbWlxZ2FELTNtVUNBd0VBQWFBdE1Dc0dDU3FHU0liM0RRRUpEakVlTUJ3d0dnWURWUjBSQkJNd0VZSVBiR0ZpWTJFdWFHOXRaUzVoY25CaE1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQTNobDVxaVk5U3NIUGh6SnhRd0lmcXZzeDdmNm5EOFRzMWJORGdjX2tqVjgzXzBNLThBVkhLajAwSE12VWticHFGUGdOb1JHSlVjV25yaC03ZGJzRmpoY2pwME1Fc2dKYXJQbk8wNk9jMjM0ZEdvQ2dCWlhSMFhfR2hiMUx4ckxBc0hkUXlueFUtUjd2TVdLX2xoREZHUDZnVENFRjF6UERTVXJmdzl3UktScHNwMFF1X1pDTC1vd3NIZWJhTFhQTlhUMDQ5a3RtdXJTWU5FZi1HemNiZUl0MmpvOHZGZ3Z1SzN0WVlZYUpkS3FaSXQwZkZmcW9DZ0twUzdTN3EzaTN5akQySV9BX0dPVnVZZEplT180Si1HRFdYRkZVUDZhVjlMVE5ybVFESktKc0l1QlV3Q0o4N09sUmdSR2xkUXJlVXl4YWNWZmtqeDQtcDFyT2RESmtEIn0", "signature": "u8Fe2qKCTaMo9yVw5b5i8lQ_eCU7t4p5y_Qbid0k6XBf8LWiq9HNoxSVXPMqR_N-zXYRqf4AaNa_e9dAkHxTThlqydHoig88hn7VUYoSQltR6E3_YaDvZ3ul44hJrrOcMjQ27ifxMt08fSNjbW_CeiCBbItsE7PiIl2psKIYJeA2szFRUCKMqbJEkeMobZeVe9P3usJyN14kLPMVYSbRc466csqrXCW50RzpipOjrFk_zbGJ6tXYdOcGBdzTgKLlxCrbLo58UlHFltE8JISeRBxzjzMJQCgnaMslhWcFUNHgOcQNr1gxv7CL-u9F7Swq2UBazWVTr6GrwVdmyqlXtDE85I-Ki0BPNwm9xLnDWjS9f-Il1UP6ZsPz9fBAQs0JZk7qXsSiYGdXyE0rF_8RjqNTTu2dnbjxFcQ_RERkm6m9ClNCUn_-gDNjYGFlB6f6Pz8TF7Ty7EgylfDbFzkKig3pgBRWAi7ZR6Iz5iRUOvXBertQkb4Z-O7yuGE53CbK-WxEUuSS08vpH11Nq3PrJEm-h7L_lygu3DORX2rMUOUB--PhuzTgOPVGXU-qjG4MaW_MzcyLzFOWiObnHidQ02kNQ6Tz-1tcbnU0cJcB5fzYJmIUb4Yp_Rx9f_mU-AW9XhlqpwbTbkMQYmO0P2VAXRql9X9I6Ki__UbEGOcdq2g"}'
Response Code: 500
Response: {'type': 'urn:ietf:params:acme:error:serverInternal', 'detail': 'Error finalizing order', 'status': 500}

**Comment by hakwerk** [comment]
This is only the client side error, it does not contain any information on why the server returns the status 500. Please have a look at the log files, also see https://github.com/hakwerk/labca/tree/master?tab=readme-ov-file#troubleshooting
