### ISSUE TITLE
Rate limit hit after two requests

### ISSUE THREAD

**Issue by dannyleeuk** [hakwerk/labca#118]
Hi, 

I've successfully create one certificate against me new LabCA - however, when attempting to create another certificate for another server on my lab environment I've hit a rate limit. Error details below (note, i have obfuscated the domain for security reasons)

`There were too many requests of a given type :: Error creating new order :: too many certificates already issued for "example.local". Retry after 2024-06-06T13:00:0`

The logs in LABCA show:

`boulder-1  | 2024-03-08T14:43:19.075234+00:00Z boulder-ra[922]: 6 boulder-ra vObtgwM Rate limit exceeded, CertificatesForDomain, regID: 2, domains: example.local`

**Comment by francescocaponio** [comment]
Hi, check the issue #117, which solves exactly this problem
