### ISSUE TITLE
Permissions issue with boulder

### ISSUE THREAD

**Issue by designworld-ca** [hakwerk/labca#119]
Installation on Ubuntu 22.04.4 went very nicely. After going to admin page completed configuration of root and intermediate. Rebooted server and returned to web page but after a long wait received "OOPS Some unexpected error occurred!"

# Diagnostic Logs: commander.logs

 Container labca-nginx-1  Restarting
 Container labca-boulder-1  Restarting
 Container labca-bmysql-1  Restarting
 Container labca-bconsul-1  Restarting
 Container labca-gui-1  Restarting
 Container labca-bconsul-1  Started
 Container labca-bmysql-1  Started
 Container labca-gui-1  Started
 Container labca-nginx-1  Started
 Container labca-boulder-1  Started
FAILED to get 21 of bin/boulder (only have 0)
FAILED to get 21 of bin/boulder (only have 3)
curl: (7) Failed to connect to boulder port 4001: Connection refused

# Docker compose logs for boulder
....
boulder-1  | Error validating config file "labca/config/va-remote-a.json" for command "boulder-remoteva": invalid character '\n' in string literal
boulder-1  | health checking rva.boulder (localhost:9397)

# docker compose logs labca

    gui-1  | 2024/03/11 00:44:17 ERROR: Message from server: 'curl: (7) Failed to connect to boulder port 4001: Connection refused 000'

boulder-1  | health checking rva.boulder (localhost:9397): grpc.health.v1.Health.Check timed out after 5000 ms

So, I think this is a permissions issue for docker but I don't know how to resolve it

**Comment by designworld-ca** [comment]
After a restart going to the admin page gives a progress bar that never completes and indicates
Restart
Almost there!
Now we will request a certificate for this website and restart one more time...

**Comment by hakwerk** [comment]
This seems to be a configuration issue, in particular the invalid character '\n' in  "labca/config/va-remote-a.json".

Please have a look at file "/home/labca/admin/data/config.json", the value for "dns" under "labca" should be a single ip address (or hostname) plus port, e.g.
```
"dns": "11.22.33.44:53",
```

After correcting that, you can run the install script again to apply the updated config to boulder (including that va-remote-a.json file).

As long as the config is not corrected, the boulder engine will not start up and as a consequence the GUI will not start up. The connection refused error is not permission related but a simple result of the process that should be listening on port 4001 is not running

**Comment by designworld-ca** [comment]
Thank you for your prompt reply!  I reverted to a previous snapshot twice but get a similar but different error
the current config.json has a blank value for server, could that be relevant?
  "labca": {
    "dns": "192.168.0.1:53",
    "domain_mode": "lockdown",
    "fqdn": "aaa.bbb.local",
    "ld_public_contacts": true,
    "lockdown": "bbb.local",
    "organization": "bbb"
  },
  "server": {
    "addr": "0.0.0.0",
    "port": 3000,
    "session": {
      "maxage": 3600
    }
I completed issuing the primary and intermediary certificates and then moved on to the restart where it hung and issued this error log

(control)/logs/commander.log

 Container labca-nginx-1  Restarting
 Container labca-boulder-1  Restarting
 Container labca-bmysql-1  Restarting
 Container labca-bconsul-1  Restarting
 Container labca-gui-1  Restarting
 Container labca-bconsul-1  Started
 Container labca-bmysql-1  Started
 Container labca-gui-1  Started
 Container labca-nginx-1  Started
 Container labca-boulder-1  Started
FAILED to get 21 of bin/boulder (only have 1)
FAILED to get 21 of bin/boulder (only have 0)
curl: (7) Failed to connect to boulder port 4001: Connection refused
docker compose logs control

control-1  | Selecting previously unselected package cron.
control-1  | (Reading database ... 
(Reading database ... 5%
...
(Reading database ... 100%
(Reading database ... 20928 files and directories currently installed.)
control-1  | Preparing to unpack .../cron_3.0pl1-136ubuntu1_amd64.deb ...
control-1  | Unpacking cron (3.0pl1-136ubuntu1) ...
control-1  | Setting up cron (3.0pl1-136ubuntu1) ...
control-1  | Adding group `crontab' (GID 108) ...
control-1  | Done.
control-1  | invoke-rc.d: could not determine current runlevel
control-1  | invoke-rc.d: policy-rc.d denied execution of start.
control-1  | Created symlink /etc/systemd/system/multi-user.target.wants/cron.service → /lib/systemd/system/cron.service.
control-1  | Processing triggers for systemd (245.4-4ubuntu3.23) ...
control-1  |  * Starting periodic command scheduler cron
control-1  |    ...done.
control-1  | 
control-1  | WARNING: apt does not have a stable CLI interface. Use with caution in scripts.
control-1  | 
control-1  | Hit:1 http://archive.ubuntu.com/ubuntu focal InRelease
control-1  | Hit:2 http://archive.ubuntu.com/ubuntu focal-updates InRelease
control-1  | Hit:3 http://archive.ubuntu.com/ubuntu focal-backports InRelease
control-1  | Hit:4 https://download.docker.com/linux/ubuntu focal InRelease
control-1  | Hit:5 http://security.ubuntu.com/ubuntu focal-security InRelease
control-1  | Reading package lists...
control-1  | Building dependency tree...
control-1  | Reading state information...
control-1  | 13 packages can be upgraded. Run 'apt list --upgradable' to see them.
control-1  | 
control-1  | WARNING: apt does not have a stable CLI interface. Use with caution in scripts.
control-1  | 
control-1  | Reading package lists...
control-1  | Building dependency tree...
control-1  | Reading state information...
control-1  | The following NEW packages will be installed:
control-1  |   ucspi-tcp
control-1  | 0 upgraded, 1 newly installed, 0 to remove and 13 not upgraded.
control-1  | Need to get 71.3 kB of archives.
control-1  | After this operation, 391 kB of additional disk space will be used.
control-1  | Get:1 http://archive.ubuntu.com/ubuntu focal/universe amd64 ucspi-tcp amd64 1:0.88-6 [71.3 kB]
control-1  | debconf: delaying package configuration, since apt-utils is not installed
control-1  | Fetched 71.3 kB in 0s (383 kB/s)
control-1  | Selecting previously unselected package ucspi-tcp.
control-1  | (Reading database ... 
(Reading database ... 5%
...
(Reading database ... 100%
(Reading database ... 20965 files and directories currently installed.)
control-1  | Preparing to unpack .../ucspi-tcp_1%3a0.88-6_amd64.deb ...
control-1  | Unpacking ucspi-tcp (1:0.88-6) ...
control-1  | Setting up ucspi-tcp (1:0.88-6) ...
control-1  | /opt/labca
control-1  | Start serving commander script...
control-1  | Generating RSA private key, 4096 bit long modulus (2 primes)
control-1  | ..........................................................................................++++
control-1  | ...............................................................................................................................................................++++
control-1  | e is 65537 (0x010001)
ok
docker compose logs boulder

boulder-1  | health checking rva.boulder (localhost:9397)
boulder-1  | health checking rva.boulder (localhost:9397): grpc.health.v1.Health.Check timed out after 5000 ms
boulder-1  | health checking rva.boulder (localhost:9397)
boulder-1  | health checking rva.boulder (localhost:9397): grpc.health.v1.Health.Check timed out after 5000 ms
boulder-1  | health checking rva.boulder (localhost:9397)
boulder-1  | health checking rva.boulder (localhost:9397): grpc.health.v1.Health.Check timed out after 5000 ms
boulder-1  | health checking rva.boulder (localhost:9397)
boulder-1  | health checking rva.boulder (localhost:9397): grpc.health.v1.Health.Check timed out after 3933 ms
boulder-1  | health checking rva.boulder (localhost:9397)
boulder-1  | health checking rva.boulder (localhost:9397): grpc.health.v1.Health.Check timed out after 0 ms
boulder-1  | 2024-03-11T19:34:32.527243+00:00Z health-checker[806]: 3 health-checker 0In0kwM [AUDIT] timed out waiting for localhost:9397 health check
boulder-1  | Starting service nonce-service-taro-1
boulder-1  | Starting service boulder-remoteva-a
boulder-1  | Error starting service boulder-remoteva-a: Command '['./bin/health-checker', '-addr', 'localhost:9397', '-host-override', 'rva.boulder', '-config', 'labca/config/health-checker.json']' returned non-zero exit status 1.
boulder-1  |  * Starting enhanced syslogd rsyslogd
boulder-1  |    ...done.
boulder-1  | Connected to boulder-mysql:3306
boulder-1  | 
boulder-1  | [0;34;1mboulder_sa_test[0m
boulder-1  | Already exists - skipping create
boulder-1  | Applied 0 migrations
boulder-1  | ERROR 1146 (42S02) at line 37: Table 'boulder_sa_test.replacementOrders' doesn't exist
boulder-1  | ERROR 1146 (42S02) at line 58: Table 'boulder_sa_test.replacementOrders' doesn't exist
boulder-1  | Added users from ../db-users/boulder_sa.sql
boulder-1  | 
boulder-1  | [0;34;1mboulder_sa_integration[0m
boulder-1  | Already exists - skipping create
boulder-1  | Applied 0 migrations
boulder-1  | ERROR 1146 (42S02) at line 37: Table 'boulder_sa_integration.replacementOrders' doesn't exist
boulder-1  | ERROR 1146 (42S02) at line 58: Table 'boulder_sa_integration.replacementOrders' doesn't exist
boulder-1  | Added users from ../db-users/boulder_sa.sql
boulder-1  | 
boulder-1  | [0;34;1mincidents_sa_test[0m
boulder-1  | Already exists - skipping create
boulder-1  | Applied 0 migrations
boulder-1  | Added users from ../db-users/incidents_sa.sql
boulder-1  | 
boulder-1  | [0;34;1mincidents_sa_integration[0m
boulder-1  | Already exists - skipping create
boulder-1  | Applied 0 migrations
boulder-1  | Added users from ../db-users/incidents_sa.sql
boulder-1  | 
boulder-1  | database setup complete
boulder-1  | CKR_SLOT_ID_INVALID: Slot 0 does not exist.
boulder-1  | Found slot 1092664829 with matching token label.
boulder-1  | The key pair has been imported.
boulder-1  | CKR_SLOT_ID_INVALID: Slot 1 does not exist.
boulder-1  | echo bin/admin bin/boulder-wfe2 bin/contact-auditor bin/bad-key-revoker bin/expiration-mailer bin/caa-log-checker bin/reversed-hostname-checker bin/boulder-ra bin/boulder bin/crl-checker bin/rocsp-tool bin/id-exporter bin/ceremony bin/boulder-observer bin/boulder-ca bin/crl-updater bin/boulder-va bin/notify-mailer bin/mail-tester bin/log-validator bin/crl-storer bin/ocsp-responder bin/nonce-service bin/admin-revoker bin/akamai-purger bin/boulder-sa bin/boulder-publisher bin/cert-checker
boulder-1  | bin/admin bin/boulder-wfe2 bin/contact-auditor bin/bad-key-revoker bin/expiration-mailer bin/caa-log-checker bin/reversed-hostname-checker bin/boulder-ra bin/boulder bin/crl-checker bin/rocsp-tool bin/id-exporter bin/ceremony bin/boulder-observer bin/boulder-ca bin/crl-updater bin/boulder-va bin/notify-mailer bin/mail-tester bin/log-validator bin/crl-storer bin/ocsp-responder bin/nonce-service bin/admin-revoker bin/akamai-purger bin/boulder-sa bin/boulder-publisher bin/cert-checker
boulder-1  | GOBIN=/opt/boulder/bin GO111MODULE=on go install -mod=vendor -buildvcs=false -tags "integration" ./...
ok
docker compose logs labca

gui-1  | 2024/03/11 19:34:11 GET /final
gui-1  | 2024/03/11 19:34:16 GET /final
gui-1  | 2024/03/11 19:34:21 GET /final
gui-1  | 2024/03/11 19:34:26 GET /final
gui-1  | 2024/03/11 19:34:31 GET /final
gui-1  | 2024/03/11 19:34:36 GET /final
gui-1  | 2024/03/11 19:34:41 GET /final
gui-1  | 2024/03/11 19:34:46 GET /final
gui-1  | 2024/03/11 19:34:51 GET /final
gui-1  | 2024/03/11 19:34:55 ERROR: Message from server: 'curl: (7) Failed to connect to boulder port 4001: Connection refused 000'
gui-1  | 2024/03/11 19:34:55 errorHandler: err=curl: (7) Failed to connect to boulder port 4001: Connection refused 000
gui-1  | main._hostCommand({0x1398458, 0xc0000bc620}, 0x41a248?, {0xe51c8f, 0xc}, {0x0, 0x0, 0xc1359c?})
gui-1  | 	/go/src/labca/main.go:2264 +0x67a
gui-1  | main.finalHandler({0x1398458?, 0xc0000bc620}, 0xc000c73900)
gui-1  | 	/go/src/labca/main.go:2813 +0x62f
gui-1  | net/http.HandlerFunc.ServeHTTP(0xd2cc40?, {0x1398458?, 0xc0000bc620?}, 0xc0000bc620?)
gui-1  | 	/usr/local/go/src/net/http/server.go:2136 +0x29
gui-1  | main.authorized.func1({0x1398458, 0xc0000bc620}, 0xc000c73900)
gui-1  | 	/go/src/labca/main.go:3289 +0x337
gui-1  | net/http.HandlerFunc.ServeHTTP(0xc000c73800?, {0x1398458?, 0xc0000bc620?}, 0x7fe0484b7db8?)
gui-1  | 	/usr/local/go/src/net/http/server.go:2136 +0x29
gui-1  | github.com/gorilla/mux.(*Router).ServeHTTP(0xc0000006c0, {0x1398458, 0xc0000bc620}, 0xc000c73700)
gui-1  | 	/root/go/pkg/mod/github.com/gorilla/mux@v1.8.0/mux.go:210 +0x1c5
gui-1  | net/http.serverHandler.ServeHTTP({0xc0002d1860?}, {0x1398458?, 0xc0000bc620?}, 0x6?)
gui-1  | 	/usr/local/go/src/net/http/server.go:2938 +0x8e
gui-1  | net/http.(*conn).serve(0xc0002a3710, {0x139b0f8, 0xc000ca07b0})
gui-1  | 	/usr/local/go/src/net/http/server.go:2009 +0x5f4
gui-1  | created by net/http.(*Server).Serve in goroutine 1
gui-1  | 	/usr/local/go/src/net/http/server.go:3086 +0x5cb
gui-1  | 2024/03/11 19:34:56 GET /final
gui-1  | 2024/03/11 19:34:56 http: superfluous response.WriteHeader call from main.finalHandler (main.go:2816)
gui-1  | 2024/03/11 19:35:01 GET /final
gui-1  | 2024/03/11 19:35:01 GET /error
gui-1  | 2024/03/11 19:35:01 errorHandler: err=<nil>
gui-1  | main.showErrorHandler({0x1398458?, 0xc0000bc540?}, 0xc00019d988?)
gui-1  | 	/go/src/labca/main.go:2842 +0x27
gui-1  | net/http.HandlerFunc.ServeHTTP(0xd2cc40?, {0x1398458?, 0xc0000bc540?}, 0xc0000bc540?)
gui-1  | 	/usr/local/go/src/net/http/server.go:2136 +0x29
gui-1  | main.authorized.func1({0x1398458, 0xc0000bc540}, 0xc000324b00)
gui-1  | 	/go/src/labca/main.go:3289 +0x337
gui-1  | net/http.HandlerFunc.ServeHTTP(0xc000324a00?, {0x1398458?, 0xc0000bc540?}, 0x7fe0484b7bc8?)
gui-1  | 	/usr/local/go/src/net/http/server.go:2136 +0x29
gui-1  | github.com/gorilla/mux.(*Router).ServeHTTP(0xc0000006c0, {0x1398458, 0xc0000bc540}, 0xc000324900)
gui-1  | 	/root/go/pkg/mod/github.com/gorilla/mux@v1.8.0/mux.go:210 +0x1c5
gui-1  | net/http.serverHandler.ServeHTTP({0xc000910450?}, {0x1398458?, 0xc0000bc540?}, 0x6?)
gui-1  | 	/usr/local/go/src/net/http/server.go:2938 +0x8e
gui-1  | net/http.(*conn).serve(0xc0002947e0, {0x139b0f8, 0xc000ca07b0})
gui-1  | 	/usr/local/go/src/net/http/server.go:2009 +0x5f4
gui-1  | created by net/http.(*Server).Serve in goroutine 1
gui-1  | 	/usr/local/go/src/net/http/server.go:3086 +0x5cb
ok
v24.03

**Comment by hakwerk** [comment]
> the current config.json has a blank value for server, could that be relevant?

Actually, server is a structure with several fields (addr, port and session) below it, so that snippet of config is looking fine.

But for some reason boulder is not happy about its derived configs. You can try removing the boulder container and have it recreated:
```
docker compose stop boulder
docker compose rm -f boulder
docker compose up -d
```

Sometimes that helps for some reason. If that has no effect either, then the relevant info will be in the `docker compose logs boulder` output. Just before those "grpc.health.v1.Health.Check timed out after 5000 ms" lines, it should say what the issue is why the boulder processes will not start.
If that is still the "invalid character '\n' in string literal" issue in labca/config/va-remote-a.json message, then we should have a look at the file /home/labca/boulder_labca/config/va-remote-a.json, it should look something like this:
```
{
        "va": {
                "userAgent": "boulder-remote-a",
                "debugAddr": ":8011",
                "dnsTries": 3,
                "dnsStaticResolvers": [
                        "192.168.0.1:53"
                ],
                "dnsTimeout": "3s",
                "dnsAllowLoopbackAddresses": true,
                "issuerDomain": "bbb.local",
                "tls": {
                        "caCertfile": "labca/grpc-creds/minica.pem",
                        "certFile": "labca/grpc-creds/rva.boulder/cert.pem",
                        "keyFile": "labca/grpc-creds/rva.boulder/key.pem"
                },
                "grpc": {
                        "address": ":9097",
                        "services": {
                                "va.VA": {
                                        "clientNames": [
                                                "va.boulder"
                                        ]
                                },
                                "grpc.health.v1.Health": {
                                        "clientNames": [
                                                "health-checker.boulder"
                                        ]
                                }
                        }
                },
                "features": {},
                "accountURIPrefixes": [
                        "http://aaa.bbb.local/acme/reg/",
                        "http://aaa.bbb.local/acme/acct/"
                ],
                "labcaDomains": [
                        "bbb.local"
                ]
        },
        "syslog": {
                "stdoutlevel": 6,
                "sysloglevel": 4
        }
}
```

**Comment by designworld-ca** [comment]
Thank you again for your help.
# Recreated boulder using docker 

To save a long, long log file it seemed to go well and ended with
✔ Container labca-bmysql-1   Running                                                                                                                                                         0.0s
✔ Container labca-gui-1      Started                                                                                                                                                        
18.8s
✔ Container labca-bconsul-1  Running                                                                                                                                                         
0.0s
✔ Container labca-boulder-1  Started                                                                                                                                                        18.8s
✔ Container labca-nginx-1    Running                                                                                                                                                         0.0s
✔ Container labca-control-1  Started        

# Boulder compose file is invalid
root@dnsbox:/home/labca/boulder# docker-compose logs boulder
ERROR: The Compose file './docker-compose.yml' is invalid because:
'name' does not match any of the regexes: '^x-'

### could this be the FAKE_DNS entry is not correct? should the ACME client be installed?


# Docker-compose.yml

    version: '3'
name: labca
services:
  boulder:
    # The `letsencrypt/boulder-tools:latest` tag is automatically built in local
    # dev environments. In CI a specific BOULDER_TOOLS_TAG is passed, and it is
    # pulled with `docker compose pull`.
    image: &boulder_image letsencrypt/boulder-tools:${BOULDER_TOOLS_TAG:-latest}
    build:
      context: test/boulder-tools/
      # Should match one of the GO_DEV_VERSIONS in test/boulder-tools/tag_and_upload.sh.
      args:
        GO_VERSION: 1.21.5
    environment:
      # To solve HTTP-01 and TLS-ALPN-01 challenges, change the IP in FAKE_DNS
      # to the IP address where your ACME client's solver is listening.
      # FAKE_DNS: 172.17.0.1
      FAKE_DNS: 10.77.77.77
      BOULDER_CONFIG_DIR: labca/config
      GOCACHE: /boulder/.gocache/go-build
      GOFLAGS: -mod=vendor
      # Forward the parent env's GOEXPERIMENT value into the container.
      GOEXPERIMENT: ${GOEXPERIMENT:-}
    volumes:
      - .:/opt/boulder:cached
      - /home/labca/boulder_labca:/opt/boulder/labca
      - /home/labca/nginx_data/static:/opt/wwwstatic
      - ./.gocache:/root/.cache/go-build:cached
      - ./.hierarchy:/hierarchy/:cached
      - ./.softhsm-tokens/:/var/lib/softhsm/tokens/:cached
    networks:
      bouldernet:
        ipv4_address: 10.77.77.77
      integrationtestnet:
        ipv4_address: 10.88.88.88
      consulnet:
        ipv4_address: 10.55.55.55
    # Use consul as a backup to Docker's embedded DNS server. If there's a name
    # Docker's DNS server doesn't know about, it will forward the query to this
    # IP (running consul).
    # (https://docs.docker.com/config/containers/container-networking/#dns-services).
    # This is used to look up service names via A records (like ra.service.consul) that
    # are configured via the ServerAddress field of cmd.GRPCClientConfig.
    # TODO: Remove this when ServerAddress is deprecated in favor of SRV records
    # and DNSAuthority.
    dns: 10.55.55.10
    expose:
      - 4001 # ACMEv2
      - 4002 # OCSP
      - 4003 # OCSP
    depends_on:
      - bmysql
      - bconsul
    entrypoint: labca/entrypoint.sh
    working_dir: &boulder_working_dir /opt/boulder
    logging:
      driver: "json-file"
      options:
        max-size: "500k"
        max-file: "5"
    restart: always

  bmysql:
    image: mariadb:10.5
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      bouldernet:
        aliases:
          - boulder-mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    # Send slow queries to a table so we can check for them in the
    # integration tests. For now we ignore queries not using indexes,
    # because that seems to trigger based on the optimizer's choice to not
    # use an index for certain queries, particularly when tables are still
    # small.
    command: mysqld --bind-address=0.0.0.0 --slow-query-log --log-output=TABLE --log-queries-not-using-indexes=ON
    logging:
      driver: "json-file"
      options:
        max-size: "500k"
        max-file: "5"
    restart: always

  bconsul:
    image: hashicorp/consul:1.15.4
    volumes:
     - ./test/:/test/:cached
    networks:
      consulnet:
        ipv4_address: 10.55.55.10
      bouldernet:
        ipv4_address: 10.77.77.10
    command: "consul agent -dev -config-format=hcl -config-file=/test/consul/config.hcl"
    restart: always

  gui:
    image: *boulder_image
    networks:
      - bouldernet
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/labca/admin:/go/src/labca
      - ./.gocache:/root/.cache/go-build
      - /home/labca/nginx_data/static:/opt/wwwstatic
      - /home/labca/backup:/opt/backup
      - .:/opt/boulder
      - /home/labca/boulder_labca:/opt/boulder/labca
    expose:
      - 3000
    depends_on:
      - bmysql
    working_dir: /go/src/labca
    command: ./setup.sh
    logging:
      driver: "json-file"
      options:
        max-size: "500k"
        max-file: "5"
    restart: always

  nginx:
    image: nginx:1.25.4
    restart: always
    networks:
      - bouldernet
    ports:
      - 80:80
      - 443:443
    volumes:
      - /home/labca/nginx_data/conf.d:/etc/nginx/conf.d
      - /home/labca/nginx_data/ssl:/etc/nginx/ssl
      - /home/labca/nginx_data/static:/var/www/html

  control:
    image: *boulder_image
    networks:
      - bouldernet
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/labca/admin/data:/opt/labca/data
      - /home/labca/admin/data:/opt/labca/gui/data
      - /home/labca/admin/bin:/opt/labca/bin
      - /home/labca/labca:/opt/labca
      - /home/labca/backup:/opt/backup
      - /home/labca/control_logs:/opt/logs
      - .:/opt/boulder
      - /home/labca/boulder_labca:/opt/boulder/labca
      - /home/labca/nginx_data/conf.d:/etc/nginx/conf.d
      - /home/labca/nginx_data/ssl:/etc/nginx/ssl
      - /home/labca/nginx_data/static:/var/www/html
    expose:
      - 3030
    environment:
      LABCA_FQDN: dnsbox.designworld.local
    working_dir: /opt/labca
    command: ./control.sh
    restart: always

volumes:
  dbdata:

networks:
      # This network is primarily used for boulder services. It is also used by
      # challtestsrv, which is used in the integration tests.
  bouldernet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.77.77.0/24

      # This network is used for two things in the integration tests:
      #  - challtestsrv binds to 10.88.88.88:443 for its tls-alpn-01 challenge
      #    responder, to avoid interfering with the HTTPS port used for testing
      #    HTTP->HTTPS redirects during http-01 challenges. Note: this could
      #    probably be updated in the future so that challtestsrv can handle
      #    both tls-alpn-01 and HTTPS on the same port.
      #  - test/v2_integration.py has some test cases that start their own HTTP
      #    server instead of relying on challtestsrv, because they want very
      #    specific behavior. For these cases, v2_integration.py creates a Python
     #    HTTP server and binds it to 10.88.88.88:80.
  integrationtestnet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.88.88.0/24

  consulnet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.55.55.0/24

**Comment by hakwerk** [comment]
> root@dnsbox:/home/labca/boulder# docker-compose logs boulder

`docker-compose` (with the minus in between) is the old command which does not support the name: attribute, you should use `docker compose` (two separate words) which is more modern

**Comment by designworld-ca** [comment]
well that gives much more logging. the only error is

     Error validating config file "labca/config/va-remote-a.json" for command "boulder-remoteva": invalid character '\n' in string literal

I cannot find this file:  labca/config/va-remote-a.json

**Comment by hakwerk** [comment]
If you installed with the `install` script then it is in /home/labca/boulder_labca/config/va-remote-a.json

Otherwise it will be inside a docker volume, this should show what it contains currently:
```
docker compose exec boulder cat labca/config/va-remote-a.json
```

**Comment by designworld-ca** [comment]
I reverted to a pre install snapshot and reinstalled as root from scratch and used sudo ~labca/labca/install afterwards to update a few packages.  I got the same error
Error validating config file "labca/config/va-remote-b.json" for command "boulder-remoteva": invalid character '\n' in string literal
I checked the file and there are \n characters, just carriage return and line feeds so I believe this is due to the server where labca is installed is also one of the dns servers.  I will start from scratch with a dedicated Ubuntu server and report back.

**Comment by designworld-ca** [comment]
The labca/config/va-remote_b.json file
{
        "va": {
                "userAgent": "boulder-remote-b",
                "debugAddr": ":8012",
                "dnsTries": 3,
                "dnsStaticResolvers": [
                        "192.168.0.155:53
    fqdn: aaa.bbb.local"
                ],
                "dnsTimeout": "3s",
                "dnsAllowLoopbackAddresses": true,
                "issuerDomain": "bbb.local",
                "tls": {
                        "caCertfile": "labca/grpc-creds/minica.pem",
                        "certFile": "labca/grpc-creds/rva.boulder/cert.pem",
                        "keyFile": "labca/grpc-creds/rva.boulder/key.pem"
                },
                "grpc": {
                        "address": ":9498",
                        "services": {
                                "va.VA": {
                                        "clientNames": [
                                                "va.boulder"
                                        ]
                                },
                                "grpc.health.v1.Health": {
                                        "clientNames": [
                                                "health-checker.boulder"
                                        ]
                                }
                        }
                },
                "features": {},
                "accountURIPrefixes": [
                        "http://aaa.bbb.local/acme/reg/",
                        "http://aaa.bbb.local/acme/acct/"
                ],
                "labcaDomains": [
                        "bbb.local"
                ]
        },
        "syslog": {
                "stdoutlevel": 6,
                "sysloglevel": 4
        }
}

**Comment by hakwerk** [comment]
Hmm, for some reason the dnsStaticResolvers not only contains the DNS server but also the fqdn??
This:
```
"dnsStaticResolvers": [
"192.168.0.155:53
fqdn: aaa.bbb.local"
],
```
should be this:
```
"dnsStaticResolvers": [
"192.168.0.155:53"
],
```

I'm assuming that your example "aaa.bbb.local" in reality contains "dns" somewhere in it, correct? Looks like my parsing of the config file is too simplistic and includes your fqdn while looking for the value of the dns server setting

**Comment by designworld-ca** [comment]
I reverted to a pre install snapshot. Patched Ubuntu 22.04 with the latest and reinstalled with the curl command line.  I then used the ~labca/labca/install command just to be sure today's patch was included.

## Data entered:  

1. fqdn for the PKI Server: dnsbox.mydomain.local which is at 192.168.0.155 and is also running a bind server for internal DNS

2. DNS Server entered: 192.168.0.1 

This router has these two DNS servers configured

First 192.168.0.155 for internal
Second External DNS like 9.9.9.9

## The va-remote-a.json and va-remote-b.json files look like this

```
    {
        "va": {
                "userAgent": "boulder-remote-a",
                "debugAddr": ":8011",
                "dnsTries": 3,
                "dnsStaticResolvers": [
                        "192.168.0.1:53
    fqdn: dnsbox.mydomain.local"
                ],
                "dnsTimeout": "3s",
                "dnsAllowLoopbackAddresses": true,
                "issuerDomain": "mydomain.local",
                "tls": {
                        "caCertfile": "labca/grpc-creds/minica.pem",
                        "certFile": "labca/grpc-creds/rva.boulder/cert.pem",
                        "keyFile": "labca/grpc-creds/rva.boulder/key.pem"
                },
                "grpc": {
                        "address": ":9097",
                        "services": {
                                "va.VA": {
                                        "clientNames": [
                                                "va.boulder"
                                        ]
                                },
                                "grpc.health.v1.Health": {
                                        "clientNames": [
                                                "health-checker.boulder"
                                        ]
                                }
                        }
                },
                "features": {},
                "accountURIPrefixes": [
                        "http://dnsbox.mydomain.local/acme/reg/",
                        "http://dnsbox.mydomain.local/acme/acct/"
                ],
                "labcaDomains": [
                        "mydomain.local"
                ]
        },
        "syslog": {
                "stdoutlevel": 6,
                "sysloglevel": 4
        }
}
```

Is it possible that my use case of two DNS servers is not covered and this is why the fqdn is still added?

**Comment by hakwerk** [comment]
I haven't made a new release yet, and the install script only installs releases, so it doesn't include that fix yet.

If you manually pull the latest git version and then supply the "-k" option to the install script (to keep the labca dir as is instead of checking out the latest release), then it should work:
```
cd ~labca/labca
git pull origin
./install -k
```

There is no need to revert to a snapshot in this case, you can just re-run the install script now.

**Comment by designworld-ca** [comment]
following these instructions resolved the issue, thank you!
