### ISSUE TITLE
Install failure

### ISSUE THREAD

**Issue by tmontney** [hakwerk/labca#14]
Fresh install of Ubuntu 18.04. (I am aware this says tested on Debian.)

[✓] Running as root
[✓] Package 'git' is installed
[✓] Package 'sudo' is installed
[✓] Created user 'labca'
[i] WARNING: could not set core.excludesfile...

Running `sudo -u labca git config --global core.excludesfile /home/labca/.gitignore_global` I get **fatal: cannot come back to cwd: Permission denied**.

**Comment by hakwerk** [comment]
I've made a new release, please try again. I had to make some adjustments to make it work on Ubuntu and while testing it I discovered some other things that needed improving anyway. But now it seems to be working fine.
