### ISSUE TITLE
Installer fails because of issue with curl

### ISSUE THREAD

**Issue by ThisIsTenou** [hakwerk/labca#16]
There is an issue with cloning the git repository when using the default version of curl (**libcurl3-gnutls:amd64 v7.74.0-1.2~bpo10+1**) for Debian 10.
```
[2021-05-16 15:15:30.670] [INFO ] Clone https://github.com/hakwerk/labca/ to /home/labca/labca...
fatal: unable to access 'https://github.com/hakwerk/labca/': Failed sending HTTP2 data
[2021-05-16 15:15:30.824] [FATAL] Could not clone git repository
```
This can be worked around by downgrading curl to "**libcurl3-gnutls:amd64 v7.64.0-4+deb10u2**" (`sudo apt install libcurl3-gnutls=7.64.0-4+deb10u2`).

Additional ressources:
https://superuser.com/questions/1642858/git-throws-fatal-unable-to-access-https-github-com-user-repo-git-failed-se

You might wanna implement a check for this, or mention it in the installation guide.

**Comment by hakwerk** [comment]
Thanks for reporting this, but this doesn't seem to be a LabCA specific issue but a consequence of using curl from the less stable **backports** repository. Standard debian 10 curl is indeed still working fine
