### ISSUE TITLE
Table 'boulder_sa_integration.challenges' doesn't exist

### ISSUE THREAD

**Issue by akujinnoninjin** [hakwerk/labca#17]
### Objective
Opening /admin/challenges page in WebUI to view

### Result
"OOPS, Some unexpected error occured!"

### Logs
``labca_1    | 2021/05/29 13:15:30 errorHandler: Error 1146: Table 'boulder_sa_integration.challenges' doesn't exist``

### Environment
- Fresh deployment of LabCA, clean install of Debian 10 in an LXC Container. Can be reproduced in full VM.

**Comment by akujinnoninjin** [comment]
Possibly related, LabCA application status is "stopped" in both _Dashboard > System Overview > LabCA Application_, and _Manage > System > LabCA Application_ despite everything else working fine.

**Comment by hakwerk** [comment]
This should be fixed now in the latest release (v21.06)
