### ISSUE TITLE
Boulder not starting

### ISSUE THREAD

**Issue by northshade** [hakwerk/labca#21]
Boulder fails to start after update

<pre><code>
boulder_1  | [0;34;1mChecking if boulder_sa_test exists[0m
boulder_1  | boulder_sa_test already exists - skipping create
boulder_1  | applying migrations from ./sa/_db/migrations
boulder_1  | goose: no migrations to run. current version: 20210223140000
boulder_1  | added users to boulder_sa_test
boulder_1  | 
boulder_1  | [0;34;1mChecking if boulder_sa_integration exists[0m
boulder_1  | boulder_sa_integration already exists - skipping create
boulder_1  | applying migrations from ./sa/_db/migrations
boulder_1  | goose: no migrations to run. current version: 20210223140000
boulder_1  | added users to boulder_sa_integration
boulder_1  | 
boulder_1  | database setup complete
boulder_1  | CKR_SLOT_ID_INVALID: Slot 0 does not exist.
boulder_1  | Found slot 271399638 with matching token label.
boulder_1  | The key pair has been imported.
boulder_1  | CKR_SLOT_ID_INVALID: Slot 1 does not exist.
boulder_1  | Found slot 1625483005 with matching token label.
boulder_1  | The key pair has been imported.
boulder_1  | GOBIN=/go/src/github.com/letsencrypt/boulder/bin GO111MODULE=on go install -mod=vendor -tags "integration" ./...
boulder_1  | labca/mock-vendor.go:3:8: cannot find package "." in:
boulder_1  | 	/go/src/github.com/letsencrypt/boulder/vendor/github.com/golang/mock/mockgen/model
boulder_1  | make: *** [Makefile:39: build_cmds] Error 1
boulder_1  |  * Starting enhanced syslogd rsyslogd
boulder_1  |    ...done.
boulder_1  | Connected to boulder-mysql:3306
boulder_1  | 
boulder_1  | [0;34;1mChecking if boulder_sa_test exists[0m
boulder_1  | boulder_sa_test already exists - skipping create
boulder_1  | applying migrations from ./sa/_db/migrations
boulder_1  | goose: no migrations to run. current version: 20210223140000
boulder_1  | added users to boulder_sa_test
boulder_1  | 
boulder_1  | [0;34;1mChecking if boulder_sa_integration exists[0m
boulder_1  | boulder_sa_integration already exists - skipping create
boulder_1  | applying migrations from ./sa/_db/migrations
boulder_1  | goose: no migrations to run. current version: 20210223140000
boulder_1  | added users to boulder_sa_integration
boulder_1  | 
boulder_1  | database setup complete
boulder_1  | CKR_SLOT_ID_INVALID: Slot 0 does not exist.
boulder_1  | Found slot 271399638 with matching token label.
boulder_1  | The key pair has been imported.
boulder_1  | CKR_SLOT_ID_INVALID: Slot 1 does not exist.
boulder_1  | Found slot 1625483005 with matching token label.
boulder_1  | The key pair has been imported.
boulder_1  | GOBIN=/go/src/github.com/letsencrypt/boulder/bin GO111MODULE=on go install -mod=vendor -tags "integration" ./...
boulder_1  | labca/mock-vendor.go:3:8: cannot find package "." in:
boulder_1  | 	/go/src/github.com/letsencrypt/boulder/vendor/github.com/golang/mock/mockgen/model
boulder_1  | make: *** [Makefile:39: build_cmds] Error 1
boulder_boulder_1 exited with code 1
ok
</code></pre>

**Comment by hakwerk** [comment]
Hmm, that file should have been removed as part of the upgrade. Please try removing it manually:
```
rm /home/labca/boulder_labca/mock-vendor.go
```

**Comment by northshade** [comment]
This issue was occurring after initiating an upgrade through the web interface. It appears that something occurred and stopped the upgrade from completing fully.   Running ~labca/labca/install from cmd line resolved the issue and everything is looking good now.   Thanks for the quick response and the great work!
