### ISSUE TITLE
Question: Multiple domains

### ISSUE THREAD

**Issue by fly-man-** [hakwerk/labca#24]
I have looked through the code but couldn't find the option to enable a set of domains instead of just 1 domain

Is that part not implemented in LabCA or does it need to be handled in a different way (manual edit of the config file ?)

**Comment by hakwerk** [comment]
It is now possible to enable multiple domains via the gui.

**Comment by fly-man-** [comment]
@hakwerk Thank you for the hard work, it works like a charm now
