### ISSUE TITLE
Documentation suggestion

### ISSUE THREAD

**Issue by XRSec** [hakwerk/labca#28]
Hope to have more detailed installation and configuration documents
From ssl generation verification to distribution

**Comment by hakwerk** [comment]
I don't have the time to write extensive documentation for a hobby project. There is explanation in each page of the setup wizard to guide you in the configuration and generation of the root and issuer CA certificates.

For installing the CA certificates on your devices and for generating certificates for your servers please use Google or another search engine, there is plenty of documentation on the internet on how to do that.
