### ISSUE TITLE
Missing files

### ISSUE THREAD

**Issue by spagno** [hakwerk/labca#32]
In the new boulder release there are no more the files
- test/config/wfe.json
- test/v1_integration.py

the sed commands exit with 
"Configure the boulder application...sed: can't read config/wfe.json: No such file or directory"

I've tried to modify the install removing all the sed commands regarding these 2 files but labca doesn't work

regards

**Comment by hakwerk** [comment]
Oops, I will fix that. In the mean time you can use this workaround:
```
touch /home/labca/boulder_labca/config/wfe.json
touch /home/labca/boulder_labca/v1_integration.py
```
Now install and apply-boulder scripts should be able to run.
