### ISSUE TITLE
Hanging after setup

### ISSUE THREAD

**Issue by ChrisThePCGeek** [hakwerk/labca#33]
I have installed this in Debian 11, ubuntu 20.04, 18.04, debian 10 (turnkeyLinux core) and in Debian 11 it went all through setup and generating the root CA and issuer cert but then the challenge failed over and over.  I have my internal DNS set up properly.  All other OS i list above that I tried it on go through setup and then the page hangs after generating the issuer cert, no status response or anything, eventually says timeout.  I tried rebooting, reinstalling over...still no change.

**Comment by ChrisThePCGeek** [comment]
> I have installed this in Debian 11, ubuntu 20.04, 18.04, debian 10 (turnkeyLinux core) and in Debian 11 it went all through setup and generating the root CA and issuer cert but then the challenge failed over and over. I have my internal DNS set up properly. All other OS i list above that I tried it on go through setup and then the page hangs after generating the issuer cert, no status response or anything, eventually says timeout. I tried rebooting, reinstalling over...still no change.

this is the log from boulder when it did work on debian 11
Attaching to boulder_boulder_1
boulder_1  | Connecting to ca2.boulder:9093 health service
boulder_1  | got error connecting to health service ca2.boulder:9093: grpc.health.v1.Health.Check timed out after 1001 ms
boulder_1  | Connecting to ca2.boulder:9093 health service
boulder_1  | I220223203739 boulder-ca 1f-K2Q4 Created a reloadable allow list, it was initialized with 1 entries
boulder_1  | got error connecting to health service ca2.boulder:9093: grpc.health.v1.Health.Check timed out after 1000 ms
boulder_1  | Connecting to ca2.boulder:9093 health service
boulder_1  | I220223203740 boulder-va rY7w0g8 Versions: boulder-va=(Unspecified Unspecified) Golang=(go1.17.7) BuildHost=(Unspecified)
boulder_1  | Connecting to va2.boulder:9092 health service
boulder_1  | I220223203740 boulder-ca 3Jud3wg Versions: boulder-ca=(Unspecified Unspecified) Golang=(go1.17.7) BuildHost=(Unspecified)
boulder_1  | I220223203740 boulder-ca yomhoQo loading hostname policy, sha256: a94ca259c387f4a3ae45c7cd2e579e81fe4830eddb58771ccecc68a6adb4f37d
boulder_1  | Connecting to ca1.boulder:9093 health service
boulder_1  | got error connecting to health service ca1.boulder:9093: grpc.health.v1.Health.Check timed out after 1000 ms
boulder_1  | Connecting to ca1.boulder:9093 health service
boulder_1  | got error connecting to health service ca1.boulder:9093: grpc.health.v1.Health.Check timed out after 1000 ms
boulder_1  | Connecting to ca1.boulder:9093 health service
boulder_1  | got error connecting to health service ca1.boulder:9093: grpc.health.v1.Health.Check timed out after 1000 ms
boulder_1  | Connecting to ca1.boulder:9093 health service
boulder_1  | got error connecting to health service ca1.boulder:9093: grpc.health.v1.Health.Check timed out after 1001 ms
boulder_1  | Connecting to ca1.boulder:9093 health service
boulder_1  | got error connecting to health service ca1.boulder:9093: grpc.health.v1.Health.Check timed out after 1000 ms
boulder_1  | Connecting to ca1.boulder:9093 health service
boulder_1  | I220223203745 boulder-ca 1f-K2Q4 Created a reloadable allow list, it was initialized with 1 entries
boulder_1  | got error connecting to health service ca1.boulder:9093: grpc.health.v1.Health.Check timed out after 1000 ms
boulder_1  | Connecting to ca1.boulder:9093 health service
boulder_1  | I220223203746 boulder-va rY7w0g8 Versions: boulder-va=(Unspecified Unspecified) Golang=(go1.17.7) BuildHost=(Unspecified)
boulder_1  | Connecting to va1.boulder:9092 health service
boulder_1  | I220223203746 boulder-ra wMHXpQQ Versions: boulder-ra=(Unspecified Unspecified) Golang=(go1.17.7) BuildHost=(Unspecified)
boulder_1  | I220223203746 boulder-ra yomhoQo loading hostname policy, sha256: a94ca259c387f4a3ae45c7cd2e579e81fe4830eddb58771ccecc68a6adb4f37d
boulder_1  | Connecting to ra1.boulder:9094 health service
boulder_1  | I220223203746 boulder-ra wMHXpQQ Versions: boulder-ra=(Unspecified Unspecified) Golang=(go1.17.7) BuildHost=(Unspecified)
boulder_1  | I220223203746 boulder-ra yomhoQo loading hostname policy, sha256: a94ca259c387f4a3ae45c7cd2e579e81fe4830eddb58771ccecc68a6adb4f37d
boulder_1  | Connecting to ra2.boulder:9094 health service
boulder_1  | I220223203747 ocsp-updater lO3duw8 Versions: ocsp-updater=(Unspecified Unspecified) Golang=(go1.17.7) BuildHost=(Unspecified)
boulder_1  | I220223203758 boulder-va n8761A4 [AUDIT] Attempting to validate HTTP-01 for "ca.pcgeek.lan" with GET to "http://ca.pcgeek.lan/.well-known/acme-challenge/MVilKUCrfSXm30gehmNsbz8Go0OVS85d2gikcDeoFrE"
boulder_1  | I220223203758 boulder-remoteva n8761A4 [AUDIT] Attempting to validate HTTP-01 for "ca.pcgeek.lan" with GET to "http://ca.pcgeek.lan/.well-known/acme-challenge/MVilKUCrfSXm30gehmNsbz8Go0OVS85d2gikcDeoFrE"
boulder_1  | I220223203758 boulder-remoteva n8761A4 [AUDIT] Attempting to validate HTTP-01 for "ca.pcgeek.lan" with GET to "http://ca.pcgeek.lan/.well-known/acme-challenge/MVilKUCrfSXm30gehmNsbz8Go0OVS85d2gikcDeoFrE"
boulder_1  | I220223203758 boulder-va tqeI1wc [AUDIT] Validation result JSON={"ID":"1","Requester":1,"Hostname":"ca.pcgeek.lan","Challenge":{"type":"http-01","status":"invalid","error":{"type":"dns","detail":"DNS problem: SERVFAIL looking up CAA for lan - the domain's nameservers may be malfunctioning","status":400},"token":"MVilKUCrfSXm30gehmNsbz8Go0OVS85d2gikcDeoFrE","keyAuthorization":"MVilKUCrfSXm30gehmNsbz8Go0OVS85d2gikcDeoFrE.6ugqZ6MEnfzIg6JKiWVVF6hGvzVvPk7Ky2oQ9QjC6C4","validationRecord":[{"url":"http://ca.pcgeek.lan/.well-known/acme-challenge/MVilKUCrfSXm30gehmNsbz8Go0OVS85d2gikcDeoFrE","hostname":"ca.pcgeek.lan","port":"80","addressesResolved":["192.168.99.132"],"addressUsed":"192.168.99.132"}]},"ValidationLatency":0.01,"Error":"dns :: DNS problem: SERVFAIL looking up CAA for lan - the domain's nameservers may be malfunctioning"}
boulder_1  | I220223203758 boulder-remoteva usTMwAE [AUDIT] Validation result JSON={"ID":"1","Requester":1,"Hostname":"ca.pcgeek.lan","Challenge":{"type":"http-01","status":"invalid","error":{"type":"connection","detail":"Fetching http://ca.pcgeek.lan/.well-known/acme-challenge/MVilKUCrfSXm30gehmNsbz8Go0OVS85d2gikcDeoFrE: Error getting validation data","status":400},"token":"MVilKUCrfSXm30gehmNsbz8Go0OVS85d2gikcDeoFrE","keyAuthorization":"MVilKUCrfSXm30gehmNsbz8Go0OVS85d2gikcDeoFrE.6ugqZ6MEnfzIg6JKiWVVF6hGvzVvPk7Ky2oQ9QjC6C4","validationRecord":[{"url":"http://ca.pcgeek.lan/.well-known/acme-challenge/MVilKUCrfSXm30gehmNsbz8Go0OVS85d2gikcDeoFrE","hostname":"ca.pcgeek.lan","port":"80","addressesResolved":["192.168.99.132"],"addressUsed":"192.168.99.132"}]},"ValidationLatency":0.01,"Error":"connection :: Fetching http://ca.pcgeek.lan/.well-known/acme-challenge/MVilKUCrfSXm30gehmNsbz8Go0OVS85d2gikcDeoFrE: Error getting validation data"}
boulder_1  | I220223203758 boulder-remoteva msSylw4 [AUDIT] Validation result JSON={"ID":"1","Requester":1,"Hostname":"ca.pcgeek.lan","Challenge":{"type":"http-01","status":"invalid","error":{"type":"connection","detail":"Fetching http://ca.pcgeek.lan/.well-known/acme-challenge/MVilKUCrfSXm30gehmNsbz8Go0OVS85d2gikcDeoFrE: Error getting validation data","status":400},"token":"MVilKUCrfSXm30gehmNsbz8Go0OVS85d2gikcDeoFrE","keyAuthorization":"MVilKUCrfSXm30gehmNsbz8Go0OVS85d2gikcDeoFrE.6ugqZ6MEnfzIg6JKiWVVF6hGvzVvPk7Ky2oQ9QjC6C4","validationRecord":[{"url":"http://ca.pcgeek.lan/.well-known/acme-challenge/MVilKUCrfSXm30gehmNsbz8Go0OVS85d2gikcDeoFrE","hostname":"ca.pcgeek.lan","port":"80","addressesResolved":["192.168.99.132"],"addressUsed":"192.168.99.132"}]},"ValidationLatency":0.008,"Error":"connection :: Fetching http://ca.pcgeek.lan/.well-known/acme-challenge/MVilKUCrfSXm30gehmNsbz8Go0OVS85d2gikcDeoFrE: Error getting validation data"}
boulder_1  | I220223204605 boulder-ca yomhoQo loading hostname policy, sha256: a94ca259c387f4a3ae45c7cd2e579e81fe4830eddb58771ccecc68a6adb4f37d
boulder_1  | I220223204610 boulder-ca yomhoQo loading hostname policy, sha256: a94ca259c387f4a3ae45c7cd2e579e81fe4830eddb58771ccecc68a6adb4f37d
boulder_1  | I220223204616 boulder-ra yomhoQo loading hostname policy, sha256: a94ca259c387f4a3ae45c7cd2e579e81fe4830eddb58771ccecc68a6adb4f37d
boulder_1  | I220223204616 boulder-ra yomhoQo loading hostname policy, sha256: a94ca259c387f4a3ae45c7cd2e579e81fe4830eddb58771ccecc68a6adb4f37d
boulder_1  | I220223204637 boulder-va 9rva1gw [AUDIT] Attempting to validate HTTP-01 for "ca.pcgeek.lan" with GET to "http://ca.pcgeek.lan/.well-known/acme-challenge/LJZqxvDMu9OtMeEAP9vxKaZC_934B7F8Ng8x0cKhBU8"
boulder_1  | I220223204637 boulder-remoteva 9rva1gw [AUDIT] Attempting to validate HTTP-01 for "ca.pcgeek.lan" with GET to "http://ca.pcgeek.lan/.well-known/acme-challenge/LJZqxvDMu9OtMeEAP9vxKaZC_934B7F8Ng8x0cKhBU8"
boulder_1  | I220223204637 boulder-remoteva 9rva1gw [AUDIT] Attempting to validate HTTP-01 for "ca.pcgeek.lan" with GET to "http://ca.pcgeek.lan/.well-known/acme-challenge/LJZqxvDMu9OtMeEAP9vxKaZC_934B7F8Ng8x0cKhBU8"
boulder_1  | I220223204637 boulder-remoteva -eznuQY [AUDIT] Validation result JSON={"ID":"2","Requester":1,"Hostname":"ca.pcgeek.lan","Challenge":{"type":"http-01","status":"invalid","error":{"type":"dns","detail":"DNS problem: SERVFAIL looking up CAA for lan - the domain's nameservers may be malfunctioning","status":400},"token":"LJZqxvDMu9OtMeEAP9vxKaZC_934B7F8Ng8x0cKhBU8","keyAuthorization":"LJZqxvDMu9OtMeEAP9vxKaZC_934B7F8Ng8x0cKhBU8.6ugqZ6MEnfzIg6JKiWVVF6hGvzVvPk7Ky2oQ9QjC6C4","validationRecord":[{"url":"http://ca.pcgeek.lan/.well-known/acme-challenge/LJZqxvDMu9OtMeEAP9vxKaZC_934B7F8Ng8x0cKhBU8","hostname":"ca.pcgeek.lan","port":"80","addressesResolved":["192.168.99.132"],"addressUsed":"192.168.99.132"}]},"ValidationLatency":0.005,"Error":"dns :: DNS problem: SERVFAIL looking up CAA for lan - the domain's nameservers may be malfunctioning"}
boulder_1  | I220223204637 boulder-va gLbglwY Remote VA "va1.boulder:9098".PerformValidation returned problem: dns :: DNS problem: SERVFAIL looking up CAA for lan - the domain's nameservers may be malfunctioning
boulder_1  | I220223204637 boulder-remoteva vd-w0QE [AUDIT] Validation result JSON={"ID":"2","Requester":1,"Hostname":"ca.pcgeek.lan","Challenge":{"type":"http-01","status":"invalid","error":{"type":"dns","detail":"DNS problem: SERVFAIL looking up CAA for lan - the domain's nameservers may be malfunctioning","status":400},"token":"LJZqxvDMu9OtMeEAP9vxKaZC_934B7F8Ng8x0cKhBU8","keyAuthorization":"LJZqxvDMu9OtMeEAP9vxKaZC_934B7F8Ng8x0cKhBU8.6ugqZ6MEnfzIg6JKiWVVF6hGvzVvPk7Ky2oQ9QjC6C4","validationRecord":[{"url":"http://ca.pcgeek.lan/.well-known/acme-challenge/LJZqxvDMu9OtMeEAP9vxKaZC_934B7F8Ng8x0cKhBU8","hostname":"ca.pcgeek.lan","port":"80","addressesResolved":["192.168.99.132"],"addressUsed":"192.168.99.132"}]},"ValidationLatency":0.013,"Error":"dns :: DNS problem: SERVFAIL looking up CAA for lan - the domain's nameservers may be malfunctioning"}
boulder_1  | I220223204637 boulder-va kbr7yQE [AUDIT] Validation result JSON={"ID":"2","Requester":1,"Hostname":"ca.pcgeek.lan","Challenge":{"type":"http-01","status":"invalid","error":{"type":"dns","detail":"DNS problem: SERVFAIL looking up CAA for lan - the domain's nameservers may be malfunctioning","status":400},"token":"LJZqxvDMu9OtMeEAP9vxKaZC_934B7F8Ng8x0cKhBU8","keyAuthorization":"LJZqxvDMu9OtMeEAP9vxKaZC_934B7F8Ng8x0cKhBU8.6ugqZ6MEnfzIg6JKiWVVF6hGvzVvPk7Ky2oQ9QjC6C4","validationRecord":[{"url":"http://ca.pcgeek.lan/.well-known/acme-challenge/LJZqxvDMu9OtMeEAP9vxKaZC_934B7F8Ng8x0cKhBU8","hostname":"ca.pcgeek.lan","port":"80","addressesResolved":["192.168.99.132"],"addressUsed":"192.168.99.132"}]},"ValidationLatency":0.015,"Error":"dns :: DNS problem: SERVFAIL looking up CAA for lan - the domain's nameservers may be malfunctioning"}
ok

**Comment by hakwerk** [comment]
See also issue report #23 - you need to add a CAA record to your DNS zone:
```
pcgeek.lan. CAA 0 issue "pcgeek.lan"
```

**Comment by ChrisThePCGeek** [comment]
Ahh okay I'll look into that thank you.  That might be something to note in
the setup directions.

Since my DNS is windows DNS server I did look to see if I had an option to
add that record type and I couldn't find one the normal way but now I know
that's what is needed, I can research on Google, it's probably a PowerShell
command.

**Comment by ChrisThePCGeek** [comment]
Thanks again, that resolved my issue.  If you had it in your documentation already and i missed it I apologize, if you just added it then thank you!
