### ISSUE TITLE
Install fails due to missing example-expiration-template

### ISSUE THREAD

**Issue by techgourmet** [hakwerk/labca#49]
Hi,

During the install on Debian 11, I get the following:

curl -sSL https://raw.githubusercontent.com/hakwerk/labca/master/install | bash

  [✓] Running as root
  [✓] Package 'git' is installed
  [✓] Package 'sudo' is installed
  [✓] User 'labca' already exists
  [✓] Update git repository in /home/labca/labca
  [✓] Determine web address
  [✓] Setup admin application
  [✓] Configure the admin application
  [✓] Software is up-to-date
  [✓] Package 'apt-transport-https' is installed
  [✓] Package 'ca-certificates' is installed
  [✓] Package 'curl' is installed
  [✓] Package 'gnupg2' is installed
  [✓] Package 'net-tools' is installed
  [✓] Package 'software-properties-common' is installed
  [✓] Package 'tzdata' is installed
  [✓] Package 'ucspi-tcp' is installed
  [✓] Package 'zip' is installed
  [✓] Package 'python' is installed
  [✓] Package 'docker-ce' is installed
  [✓] Binary 'docker-compose' is installed
  [✓] Static web pages
  [✓] Certificate is present
  [✓] Update git repository in /home/labca/gopath/src/github.com/letsencrypt/boulder
  [✓] Boulder checkout 'release-2022-07-05'
  [✓] Commit existing modifications of /home/labca/boulder_labca
  [✓] Setup boulder configuration folder
  **[.] Configure the boulder application...sed: can't read example-expiration-template: No such file or directory**
  
  Subsequently the install fails.

**Comment by mw8088** [comment]
In the change from boulder version 05-31 to  07-05 the name of the expiration template was changed to  [config/expiration-mailer.gotmpl](https://github.com/letsencrypt/boulder/compare/release-2022-05-31...release-2022-07-05#diff-63673b1ed843afd07bc31b10dddaea3326ebb9232a96c07c97150c9a2e9c2d46). Changing that line in the config script should fix it.

**Comment by hakwerk** [comment]
Oops, that was indeed the issue. Should be fixed now

**Comment by techgourmet** [comment]
I'll pull the updated version

**Comment by techgourmet** [comment]
[✓] Boulder checkout 'release-2022-07-05'
  [✓] Setup boulder configuration folder
  [✓] Configure the boulder application
  [✓] Cleaning up obsolete files
  [✓] Restart docker containers and service
 done!


========

Congratulations! LabCA is now installed and should be available at https://ca.finishline.lan
Please go there now to finish the setup. Note that a TEMPORARY (7 days) self-signed certificate
is used; as part of the setup verification a new certificate will be issued.
