### ISSUE TITLE
Use Step CA as an ACME server?

### ISSUE THREAD

**Issue by budulinek** [hakwerk/labca#55]
OK, I know you have invested a lot into Boulder. But still, I would like to start the discussion...

Couple of hours ago I did my very first installation of [Step CA](https://github.com/smallstep/certificates) as an ACME server. It was actually much easier than expected (follow this [guide](https://blog.sean-wright.com/self-host-acme-server/) ). 

So now I have both Boulder (LabCA) and Step CA, each within its own LXC. And a bunch of ACME clients to test them. Some quick comparison of Step CA over Boulder:

- Step CA has no limits (quite handy if you are testing things), while Boulder complains that "Error creating new order :: too many certificates (2) already issued for this exact set of domains in the last 3 hours..."
- Step CA can issue certs for an IP (quite handy for internal servers...),  compared to Boulder throwing an error "NewOrder request included invalid non-DNS type identifier: type \"ip\""
- Step CA is a full-fledged certificate authority (incl. ACME server). You can either issue certs manually (bypass domain-authorization), or use ACME protocol. Boulder is "just" an ACME server. If you [want a cert](https://github.com/hakwerk/labca/issues/22) from Boulder, you have to use ACME.
- Step CA is distributed both as a dockerfile and regular package (useful if you can not or does not want to use Docker). Boulder only comes as a dockerfile.

**Comment by hakwerk** [comment]
When I started this project in 2018, Step CA ACME did not exist yet. It's only become available about a year ago or so.

Thanks for the comparison, I haven't come around myself to trying it out. Sounds like you should stick to Step CA 😄

**Comment by budulinek** [comment]
Boulder sucks but LabCA is great... Most of my ACME clients are conneted to LabCA, but when Boulder fails to do the job, I redirect the client to Ctep CA. So at the moment I have both LabCA and Step CA running. 
Also:

- Step CA does not validate against CAA records (see . [explanation](https://github.com/smallstep/certificates/issues/887)). Boulder does.

Having LabCA with Step CA  would be great. I looked at your code but replacing Boulder with Step CA is beyond my skills (I know nothing about Go, very little about dockers).

**Comment by budulinek** [comment]
I did a bit of research on Step CA. You may find it useful in case you are considering Step  CA.

The good news:
- There is a Go wrapper for Step CA ([here](https://github.com/smallstep/certificates/tree/master/examples#user-content-basic-client-usage) and [here](https://pkg.go.dev/github.com/smallstep/certificates/ca) ). And a CLI client.
- Step CA stores data about certs, accounts, etc. in a database. You can choose your database (default is Badger DB - never heard about it...). See [here](https://smallstep.com/docs/step-ca/configuration/#databases) .
- There is also a sample Go script for accessing the Badger DB [here](https://gist.github.com/dopey/89ec20f22c66c1333bf38c9b19b89758) .

The bad news:
- Badger (the default DB) only allows one process accessing the DB. So you need to stop Step CA (or make the copy of the DB) if you want to read the data...
- At the moment, Step CA uses NoSQL storage schema (key -> value, probably stored in raw bytes...). Exploring the data may be difficult.
- Smallstep promised to swith to standard SQL schema ( [here](https://github.com/smallstep/certificates/issues/282) )  after several requests for more reporting capabilities from their users (see [here](https://github.com/smallstep/certificates/issues/239), [here](https://github.com/smallstep/certificates/issues/507), and a [discussion](https://github.com/smallstep/certificates/discussions/387)). Step CA users knew about you :-) . They asked smallstep for "web interface similar to that provided by labca" already 2 years ago ([here](https://github.com/smallstep/certificates/issues/390)) ... But so far there is neither the webinterface for Step CA (and there never will be), nor the promised SQL storage backend.  
- Instead, smallstep is pushing users towards their hosted [Certificate Manager](https://smallstep.com/certificate-manager/) service. Acording to [this post](https://github.com/smallstep/certificates/issues/507#issuecomment-800550428), while working on the commercial Certificate Manager, they have already "written a sql backend for the db which will be merged into the open source soon". That was in March 2021.  The promised merge to open source did not (yet) materialize.

If you plan to add new features to LabCA, it makes little sense to stick with Boulder. For example, if you want to renew / replace Root and Issuer CA certificates with Boulder, you need to do that manually with openssl (= danger of [misconfiguration](https://github.com/hakwerk/labca/issues/54)). With Step CA, (re)placing root is easy with one command (step ca init). On the other side, the missing SQL backend is a dealbreaker at the moment.... So my humble suggestion would be: wait with new LabCA features. Switch to Step CA once they merge their SQL backend into open source?

**Comment by hakwerk** [comment]
Actually, it turns out the current MySQL database is already quite usable! I have made a standalone version of the LabCA GUI that can work with the step-ca database to show the ACME information. The [.deb](https://github.com/hakwerk/labca/releases/download/v22.09/labca-gui_22.09_amd64.deb) is on the latest release page. More info [here](https://github.com/hakwerk/labca/blob/master/README_standalone.md).

I haven't bothered with BadgerDB, the limitation of only one process accessing it at the same time is just horrible.

I quickly tried integrating the revocation of certificates, but automating that is however not so easy. On the command line you either manually need to select the provisioner and provide the password, or provide a token for which you also need to select the provisioner and provide the password? Looking at the API documentation I haven't solved that issue. But I guess if you have this GUI you can easily lookup the serial of the certificate that you want to revoke and then do it with the step cli.

**Comment by budulinek** [comment]
Thanks a lot!

I tried to run the standalone version and got an error:

```
# labca-gui -config stepca.json -port 80 -init
panic: fatal error templates: 'templates: filepath.Walk error: lstat ./templates: no such file or directory'

goroutine 1 [running]:
main.init.0()
        /home/runner/work/labca/labca/gui/main.go:2825 +0xcfc
```
Some hard-coded path in the binary?

**Comment by hakwerk** [comment]
Hmm, there was a small bug in determining if the embedded templates should be used or the templates from a directory. Should be fixed now in the latest release (v22.09.1).
Thanks for trying it out!

**Comment by budulinek** [comment]
Hi, just want to say that it works! Thanks a lot!

I have some minor issues with web server paths:

certificate details
```
2022/11/18 22:26:01 errorHandler: err=NotFoundHandler for: GET /certificates/static/css/bootstrap.min.css
2022/11/18 22:26:01 errorHandler: err=NotFoundHandler for: GET /certificates/static/css/metisMenu.min.css
2022/11/18 22:26:01 errorHandler: err=NotFoundHandler for: GET /certificates/static/css/sb-admin-2.min.css
2022/11/18 22:26:01 errorHandler: err=NotFoundHandler for: GET /certificates/static/css/font-awesome.min.css
...
```

and account details

```
2022/11/18 22:28:31 errorHandler: err=NotFoundHandler for: GET /accounts/static/css/bootstrap.min.css
2022/11/18 22:28:31 errorHandler: err=NotFoundHandler for: GET /accounts/static/css/metisMenu.min.css
2022/11/18 22:28:31 errorHandler: err=NotFoundHandler for: GET /accounts/static/css/sb-admin-2.min.css
...
```

webpage loads but without CSS styles and stuff.

**Comment by skull-squadron** [comment]
For posterity and an update, step-ca is a FOSS-washing commercial project where useful features are locked away behind a paywall deliberately.

```
Comparison with Smallstep's commercial product
step-ca is optimized for a two-tier PKI serving common DevOps use cases.

As you design your PKI, if you need any of the following, [consider our commerical CA](http://smallstep.com/):

Multiple certificate authorities
Active revocation (CRL, OSCP)
Turnkey high-volume, high availability CA
An API for seamless IaC management of your PKI
Integrated support for SCEP & NDES, for migrating from legacy Active Directory Certificate Services deployments
Device identity — cross-platform device inventory and attestation using Secure Enclave & TPM 2.0
Highly automated PKI — managed certificate renewal, monitoring, TPM-based attested enrollment
Seamless client deployments of EAP-TLS Wi-Fi, VPN, SSH, and browser certificates
Jamf, Intune, or other MDM for root distribution and client enrollment
Web Admin UI — history, issuance, and metrics
ACME External Account Binding (EAB)
Deep integration with an identity provider
Fine-grained, role-based access control
FIPS-compliant software
HSM-bound private keys
```

**Comment by outbackdingo** [comment]
Looks nice, can someone explain about this mysql db you mention, we have stepca deployed in k8s it needs a gui for monitoring ACME, so is there  a quick and dirty howto on this ? i also see no helm charts for any of this, willing to contribute some if i can at least understand how to deploy it
