### ISSUE TITLE
Install doesnt work

### ISSUE THREAD

**Issue by antonov314** [hakwerk/labca#56]
Hi,

i try to install this super awsom project but when i try under sudo i got this message:

root@docker:/home/sysadmin# curl -sSL https://raw.githubusercontent.com/hakwerk/labca/master/install | bash

  [✓] Running as root
main: line 72: /tmp/labca-install.log: Permission denied

No idea what to do ?

trying under fresh install on Ubuntu 22.04.1 LTS
also tryed on CentOS , Oracle linux none of them work :(

**Comment by hakwerk** [comment]
I just tried on a brand new Ubuntu 22.04 vm and it works just fine. Does the /tmp directory exist?
```
ls -latr /tmp
```
And is it writable?
```
echo "hello" >/tmp/test.txt
cat /tmp/test.txt
```
How exactly are you trying the different Ubuntu / CentOS / Oracle installations? It is extremely unlikely that on all of them root has no access to /tmp

**Comment by Johndpete316** [comment]
I had a similar issue. I ran the script as a root

```
$ curl -sSL https://raw.githubusercontent.com/hakwerk/labca/master/install | sudo bash

  [✓] Running as root
main: line 72: /tmp/labca-install.log: Permission denied
```

I deleted the log file /tmp/labca-install.log
and ran the same line again and it worked just fine.

**Comment by hakwerk** [comment]
Should be fixed now
