### ISSUE TITLE
Install script command line args/options 

### ISSUE THREAD

**Issue by mwstamant** [hakwerk/labca#59]
I am attempting to run the install script autonomously and can't seem to get the command line options to work. I have attempted the following:
./install.sh -n fqdn.example.com
./install.sh -name fqdn.example.com
./install.sh -fqdn fqdn.example.com

**Comment by hakwerk** [comment]
Normally the script is just called `install` but perhaps you have renamed it. The first form should work.
When using the long form you should use two dashes: `--name` or `--fqdn`

Does the output on the screen show something like this?
```
  [✓] option: using FQDN name 'fqdn.example.com'
```

Is there anything in the latest log file in the /home/labca/logs/ directory? Or even in /tmp/labca-install-*.log ?

**Comment by mwstamant** [comment]
with -n:
<img width="1004" alt="image" src="https://user-images.githubusercontent.com/53268715/193157021-bc864cb7-17a2-4282-9ba4-e01bb4cf760e.png">
with --name:
<img width="1002" alt="image" src="https://user-images.githubusercontent.com/53268715/193157371-0edb2a52-f04b-4e35-83a2-86e928b445d9.png">
with --fqdn:
<img width="1001" alt="image" src="https://user-images.githubusercontent.com/53268715/193157543-440749a8-aa2c-4e35-b8da-a32c33303f9f.png">

/home/labca/logs/  optput:
<img width="777" alt="image" src="https://user-images.githubusercontent.com/53268715/193157831-f9001e42-180c-4a67-a155-4e3ae230d112.png">
/tmp/labca-install-*.log output:
<img width="546" alt="image" src="https://user-images.githubusercontent.com/53268715/193158275-b2ce887f-2a32-4751-bc6b-83c7f19e7bb7.png">

**Comment by hakwerk** [comment]
Hmmm, I'm unable to reproduce this issue.
But you can just put the desired name as answer to the FQDN question and hopefully it continues normally...
