### ISSUE TITLE
Rate Limit Exceeded

### ISSUE THREAD

**Issue by mwstamant** [hakwerk/labca#61]
Hello @hakwerk 👋🏻 

I am having rate limit issues on my LabCA instance and cannot determine exactly why this behaviour is occurring. 🤔

From the logs:
`boulder-boulder-1  | 2022-10-15T17:06:24.422773+00:00 99e1c457e7c4 unknown boulder-ra[663]: 6 boulder-ra kfXf6gw Rate limit exceeded, CertificatesForDomain, regID: 4, domains: example.com`

I have the LabCA domain mode set to lockdown with "int.example.com" as the domain. LabCA is connected to an internal split-dns that is authoritative for int.example.com, all other domains forward to a recursive resolver/public DNS. 

-Is the issue that the root "example.com" is a valid real-world domain?, and if so is there any way to bypass this behaviour?

Thank you so much for providing and maintaining this great tool. 🙏🏻

**Comment by hakwerk** [comment]
You can try adding example.com next to int.example.com (one per line) in the Domain mode box on the Config tab of the Manage page (URL "/admin/manage#config" in browser) and click the Update button. That should set the limit for example.com also to a high value.
