### ISSUE TITLE
Installation script stops execution after python is installed

### ISSUE THREAD

**Issue by DanAE111** [hakwerk/labca#64]
Trying to install this on a Raspbery Pi running Raspbian, everything works fine until the installation script just stops after successfully installing python.

Not exactly sure why it's deciding to just stop, is there a way the installtion script can be run with some verbosity to help track down what the potential issue may be?

**Comment by hakwerk** [comment]
There should be a log file in the /home/labca/logs/ directory.
After installing the python package the installer tries to determine the distribution and then install docker. I guess this command might be the culprit on raspbian:
```
distrib=$(lsb_release -is | tr '[:upper:]' '[:lower:]')
```

FYI: you can try making some modifications to the /home/labca/labca/install script to add e.g. debugging or extra/different commands, and then run the install script with the "-k" option to skip updating from github and overwriting your local modifications.
