### ISSUE TITLE
Dependency version inconsistency

### ISSUE THREAD

**Issue by Ben131-Go** [hakwerk/labca#65]
It is a reminder of dependency version inconsistency introduced by replace directive used in `github.com/smallstep/certificates`.
## Dependency line:
github.com/hakwerk/labca/gui --> [github.com/smallstep/certificates](https://github.com/hakwerk/labca/blob/master/gui/go.mod#L17) --> [go.mozilla.org/pkcs7](https://github.com/hakwerk/labca/blob/master/gui/go.mod#L83) <br>
github.com/smallstep/certificates v0.22.0 --> github.com/smallstep/pkcs7 5259212<br>
<https://github.com/smallstep/certificates/blob/v0.22.0/go.mod#L152>

## Background
Repo `github.com/smallstep/certificates` at version `v0.22.0` uses replace directive to pin dependency `github.com/smallstep/pkcs7` to version `5259212`.<br>
According to [Go Modules wikis](https://github.com/golang/go/wiki/Modules#when-should-i-use-the-replace-directive), `replace` directives in modules other than the `main module` are ignored when building the main module.
It means such replace usage in dependency's go.mod cannot be inherited when building main module. And it turns out that `hakwerk/labca/gui` indirectly relies on `go.mozilla.org/pkcs7@33d0574`, which is different from the pinned version `smallstep/certificates` needed.<br>
><https://github.com/hakwerk/labca/blob/master/gui/go.mod>(Line 83)
```Go
go.mozilla.org/pkcs7 v0.0.0-20210826202110-33d05740a352 // indirect
```

><https://github.com/smallstep/certificates/blob/v0.22.0/go.mod>(line 42&152)
```Go
go.mozilla.org/pkcs7 v0.0.0-20210826202110-33d05740a352
...
// use github.com/smallstep/pkcs7 fork with patches applied
replace go.mozilla.org/pkcs7 => github.com/smallstep/pkcs7 v0.0.0-20211016004704-52592125d6f6
```
It seems that `github.com/smallstep/certificates` replaces `go.mozilla.org/pkcs7` for some patches applied in `github.com/smallstep/pkcs7`.
### 1. Bump the version of dependency `github.com/smallstep/certificates`
If it doesn't cause issues at the moment, you may wait `github.com/smallstep/certificates` to eliminate the use of the replace directive and then update it.

### 2. Add the same replace rule to your go.mod
```Go
replace go.mozilla.org/pkcs7 => github.com/smallstep/pkcs7 v0.0.0-20211016004704-52592125d6f6
```
Tips: Introduce replace directive may break go install and it can not be inherited by downstream projects. So, this solution is not recommended.

**Comment by hakwerk** [comment]
Smallstep only plays a very minor role within LabCA so I don't think this is very relevant.
Not going to use a replace in my go.mod
