### ISSUE TITLE
Restarted my server. lab-ca stopped working, re-ran install/update script issue

### ISSUE THREAD

**Issue by ChrisThePCGeek** [hakwerk/labca#75]
restarted my server today to update proxmox, lab-ca vm stopped working. ran install/update script and all prior data wiped clean from db on the web ui. restored last data backup inside labca got error below.

[AUDIT] transitioning health of "sa.StorageAuthority" from "SERVING" to "NOT_SERVING", due to: failed to select one *int (unknown table): dial tcp 10.77.77.4:3306: connect: connection refused

not sure what to do

**Comment by ChrisThePCGeek** [comment]
here is an update. i Was running 23.1 version. worked fine until the vm was restarted because of server restart.  anyways, I downloaded the latest backup file, started up a new vm with new docker-compose version.  was able to restore the backup but all my accounts and prior certs arent there now. is there a way to restore that from the other server instance or do i have to re-do all my accounts?

**Comment by ChrisThePCGeek** [comment]
Another update. I just re-created my ACME accounts from the systems I needed to and issues new certs from the new version running from docker-compose.  I do wish that it would have been easier to backup the data and migrate but only the settings stayed not the whole history and revoked/expired certs.  at the end of the day its working again now.  I do also wish there was a way to upload a backup file downloaded other than just on an initial setup.

thank you for reviewing this, if you think its worth looking into at all still and need info from me feel free to re-open but for now I think my issue is resolved.

**Comment by hakwerk** [comment]
Hmm not sure what went wrong here. The backup files do include a database backup with the accounts and issued/revoked/expired cert details. I did a quick test restoring a backup on a fresh install and all the history was preserved.

First thing I notice is that you mention all history was already wiped after running install/update on your original VM. This shouldn't have happened, and I use it a lot during testing but I'll have a look if I can find out what caused that.
The error about SERVING/NOT_SERVING is within the boulder component and does not affect the web ui.

I'll also have a look at adding a way to upload backup files to make a restore easier indeed

**Comment by ChrisThePCGeek** [comment]
Thanks. I suspect it's because I went from a version a few revisions prior
to the current maybe that caused the issue somehow, maybe it was in the SQL
if the mariadb version has changed, not sure.

If it's not too complicated is there a way to use an existing mariadb or
maybe postgres instance? I have both already on my lan too.  Might be a way
in the compose file method I'm just not as versed in compose but I can do
kubernetes yaml all day haha.

Thank you so much for the help and for keeping this project going it's
really awesome.

**Comment by hakwerk** [comment]
Switching database server is not trivial. The mariadb one comes with the boulder (Let's Encrypt engine) docker-compose.yml and I bolted a GUI on top. I doubt that postgresql would work.
To connect to a different database there is a dozen or so config files that would need to be updated within the docker volumes, and they will get overwritten again on future updates.

In the mean time I have reproduced your issue by going from 23.1 to the latest version indeed, so I'll dig deeper on what exactly happens there. Restoring the backup from the GUI did not work, but manually restoring the .sql from inside the backup file worked fine. Interesting...

**Comment by ChrisThePCGeek** [comment]
Okay no worries about the external db.  Thanks so much. Glad you found the
issue and it wasn't just me

**Comment by hakwerk** [comment]
Made several improvements in preserving the data when doing an upgrade, part of release v23.07

**Comment by ChrisThePCGeek** [comment]
Thank you so much!!
