### ISSUE TITLE
Imported CA result in a error in the 2nd certtificate generation.

### ISSUE THREAD

**Issue by zimbres** [hakwerk/labca#77]
Hi I'm trying to setup and importing a CA that i already have and even using the same company name I got this error:

```
labca-gui-1  | 2023/07/05 20:35:24 POST /setup
labca-gui-1  | exit status 1: Using configuration from data/issuer/../openssl.cnf
labca-gui-1  | Check that the request matches the signature
labca-gui-1  | Signature ok
labca-gui-1  | The organizationName field is different between
labca-gui-1  | CA certificate (Zimbres DOT Com) and the request (Zimbres DOT Com)
labca-gui-1  | 2023/07/05 20:35:25 _certCreate: create failed: Error (exit status 1)! See LabCA logs for details
labca-gui-1  | main.(*CertificateInfo).Generate(0xc00088b000, {0xc0004d9258, 0xc}, {0xe51143, 0x6})
labca-gui-1  | 	/go/src/labca/certificate.go:231 +0xb85
labca-gui-1  | main.(*CertificateInfo).Create(0xc00088b000, {0xc0004d9258, 0xc}, {0xe51143, 0x6}, 0x9b?)
labca-gui-1  | 	/go/src/labca/certificate.go:628 +0x2dd
labca-gui-1  | main._certCreate({0x13872d0, 0xc00034a0e0}, 0xc00088ae00, {0xe51143?, 0x6?}, 0x0?)
labca-gui-1  | 	/go/src/labca/main.go:1893 +0x240e
labca-gui-1  | main.setupHandler({0x13872d0, 0xc00034a0e0}, 0xc00088ae00)
labca-gui-1  | 	/go/src/labca/main.go:2503 +0x20b
labca-gui-1  | ...
```

Maybe spaces are generating this error?

**Comment by hakwerk** [comment]
I suspect that your existing CA is using the type PRINTABLESTRING for the organization name where LabCA is using openssl which uses UTF8STRING.

As per [this link](https://stackoverflow.com/a/7623389) you can make this visible with
```
openssl asn1parse -in data/root-ca.pem
```
and
```
openssl asn1parse -in data/issuer/ca-int.csr
```

**Comment by hakwerk** [comment]
If so, you should probably generate the issuer certificate yourself using the existing CA, and then also upload that. When the issuer cert is used to generate the final certificates, the checks are less strict and any mismatch in utf8string vs printablestring should not be an issue

**Comment by zimbres** [comment]
@hakwerk Thank you!

PRINTABLESTRING here, also generated the issuer in XCA like the CA, got success.
