### ISSUE TITLE
First login labca can not access setup

### ISSUE THREAD

**Issue by bjtangseng** [hakwerk/labca#83]
Dear,

I hope this email finds you well. I am reaching out to report an issue I encountered while trying to set up and login to the labca software using Docker.

I successfully built the labca software using Docker without any errors, and the installation process went smoothly as well. However, when I attempted to login to the labca system, I encountered an issue where the initial setup page was not displayed correctly.

To troubleshoot this problem, I used the "docker compose log -f" command to track the logs. It appears that the connection to port 3000 is being refused.

Could you please assist me in resolving this issue? I appreciate any guidance or suggestions you can provide to help me get past this hurdle.

Thank you for your attention and support.

Best regards,

`
labca-nginx-1    | 2023/08/14 07:15:39 [error] 21#21: *3 connect() failed (111: Connection refused) while connecting to upstream, client: ::ffff:192.168.0.118, server: _, request: "GET /admin/ HTTP/1.1", upstream: "http://10.77.77.5:3000/", host: "ca.cube.net", referrer: "https://ca.cube.net/admin/"
labca-nginx-1    | ::ffff:192.168.0.118 - - [14/Aug/2023:07:15:39 +0000] "GET /admin/ HTTP/1.1" 502 7316 "https://ca.cube.net/admin/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36 Edg/115.0.1901.203" "-"
`

**Comment by hakwerk** [comment]
This can happen when the docker images are still starting up. There probably was a spinner showing in the browser and it was retrying every couple of seconds?
Please wait a couple of minutes and try using the browser again.

**Comment by keekychen** [comment]
have you solved your problem?  i met similar problem in brandy new setup ubuntu 20.04 even turn off firewall. 
![image](https://github.com/hakwerk/labca/assets/2337474/658efb35-f09a-4f55-959c-0fa818ce27e2)

**Comment by bjtangseng** [comment]
I pulled the latest docker image by re-pull. Re-running it solved it.

**Comment by hakwerk** [comment]
If the application on port 3000 is not available then you should check the gui container logs as to why: `cd /home/labca/boulder && docker compose logs -f gui`.
Most problems however show up in the logs of the boulder container, so look for some hints of what is wrong there
