### ISSUE TITLE
About support CSR Apply for a certificate

### ISSUE THREAD

**Issue by bjtangseng** [hakwerk/labca#87]
Hi

I am trying to use labca, which is a very convenient acme system. Also has a beautiful uI.

However, when I try to use a CSR to apply for a certificate, there is no path. As an internal system, not every program supports the ACME mechanism.

I would like to ask, if I want to pass the CSR file, is there any way to apply for a certificate?

**Comment by hakwerk** [comment]
LabCA only works with the ACME protocol, so using CSR is currently not supported. I may look into this in the future but right now don't have the time to do that.
