### ISSUE TITLE
Question: wrap it into docker

### ISSUE THREAD

**Issue by DavidGhiro** [hakwerk/labca#9]
Are there any plans to pack the whole thing in a Docker container?

**Comment by hakwerk** [comment]
I have been thinking about it, but it's not trivial as we start three different docker images with docker-compose. One route could be something like https://github.com/nestybox/sysbox but not sure how stable that would be. And it still requires something to be installed on your server.
Another route could be to build two images (the modified boulder plus our frontend) and have a docker-compose similar to the current one. That would take away some initial building from your server but I don't think things will become much less complex.
